### ISSUE TITLE
[lcc members] description tab missing

### ISSUE THREAD

**Issue by MatSarr** [Lokavaluto/lokavaluto-addons#143]
![image](https://user-images.githubusercontent.com/46820746/155476911-553688dc-0ae5-4685-a2cb-b27a734eb4e2.png)

the field to use already exist: website_description

and the code to use:
`<xpath expr="//page[@name='annuaire']" position="after">
   <page name="description" string="Description" attrs="{'invisible': [('is_company','=',False)]}">
      <field name="website_description" placeholder="Description détaillée du professionnel"/>
   </page>
</xpath>`

**Comment by stephansainleger** [comment]
Well in fatc it is not missing, there is an invisible constraint which is not set correctly : https://github.com/Lokavaluto/lokavaluto-addons/blob/12.0/lcc_members/views/res_partner_view.xml#L258
I thing that the right constraint should be `{'invisible': [('is_public_profile','=',False)]}`, in order to display this page only for public profiles

**Comment by MatSarr** [comment]
Visible in public profil. Will be okay when the displayed data in gogocarto will be from public profil
