### ISSUE TITLE
0€ membership invoice won't change the membership state

### ISSUE THREAD

**Issue by MatSarr** [Lokavaluto/lokavaluto-addons#67]
On https://laroue.v12.dev.myceliandre.fr 

I create an 0€ invoice from contact Elabore tab membership

In the invoice the state is "paid member" and it's good.

But the state in the res partner contact stay "old member"

![image](https://user-images.githubusercontent.com/46820746/109670583-8bb0b000-7b73-11eb-82f9-27eaa7f34ac0.png)

Expected behaviour : the state change to "paid member" even if the invoice is set to 0€

**Comment by njeudy** [comment]
Hello, I found the problem. Odoo detect if membship is paid on payment.line from invoice, but with amount = 0 , there is no payment line.

So I decide to update membership function and if invoice line is 0 so, membship state become free member (not paid because nothing was paid.) Free member is considered as member in odoo .  si I think it's true ..

**Comment by MatSarr** [comment]
@njeudy thank you for your answer. The problem of free member is that there is no period of validity.
The purpose of creating a 0€ invoice was to make sure that at the end of the membership period (linked to the article of the invoice) the contact won't be a member anymore.
If the contact is a free member, it will stay free member till someone uncheck the box and that's a problem

**Comment by njeudy** [comment]
No onset free membre without checking thé boolean. . juste state = free member si tu use date start ans date stop
